// /api/predictor.js
// World Cup 2026 Match Predictor — Vercel KV backend
//
// SETUP:
//   1. vercel kv create wc2026
//   2. vercel env pull .env.local   (adds KV_URL, KV_REST_API_URL, KV_REST_API_TOKEN etc.)
//   3. npm install @vercel/kv
//
// ACTIONS (all via GET or POST ?action=...):
//   register   POST  { userId, name }          → saves display name
//   getUser    GET   ?userId=...               → { userId, name }
//   savePred   POST  { userId, matchId, hg, ag } → saves one prediction
//   getPreds   GET   ?userId=...               → { [matchId]: {hg,ag} }
//   score      POST  { matchId, hg, ag }       → scores all predictions for a finished match (call from admin/cron)
//   leaderboard GET                            → [ { userId, name, pts, exact, correct } ... ]
//   allPreds   GET   ?matchId=...              → everyone's predictions for a match (revealed after FT)

import { Redis } from "@upstash/redis";
const kv = new Redis({
  url: process.env.KV_REST_API_URL,
  token: process.env.KV_REST_API_TOKEN,
});

// ── Score calculation (same logic as frontend) ────────────────────────────
function calcScore(pred, actual) {
  const ph = parseInt(pred.hg), pa = parseInt(pred.ag);
  const ah = parseInt(actual.hg), aa = parseInt(actual.ag);
  if (isNaN(ph) || isNaN(pa)) return null;
  if (ph === ah && pa === aa) return 3;
  const pr = ph > pa ? "H" : ph < pa ? "A" : "D";
  const ar = ah > aa ? "H" : ah < aa ? "A" : "D";
  return pr === ar ? 1 : 0;
}

// ── CORS helper ───────────────────────────────────────────────────────────
function cors(res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
}

function normName(name) {
  return String(name || "").trim().toLowerCase();
}

async function findUserByName(name) {
  const target = normName(name);
  if (!target) return null;
  let cursor = 0;
  do {
    const [nextCursor, keys] = await kv.scan(cursor, { match: "user:*", count: 100 });
    cursor = parseInt(nextCursor) || 0;
    for (const key of keys) {
      const uid = key.replace("user:", "");
      const user = await kv.get(key);
      if (user && normName(user.name) === target) return { uid, user };
    }
  } while (cursor !== 0);
  return null;
}

// Computes a user's pts/exact/correct/predCount the old (expensive) way,
// for a record that predates storing those fields directly on the user
// object. Shared by leaderboard's self-heal and the register name-merge
// path below — without this, a pre-migration user merged via the
// auto-dedup logic before their own leaderboard self-heal ever ran would
// silently lose their accumulated score (the merge would just see
// `undefined` fields and treat them as zero).
async function computeLegacyTotals(uid) {
  const scoreKeys = [];
  let cursor = 0;
  do {
    const [nc, ks] = await kv.scan(cursor, { match: `score:${uid}:*`, count: 100 });
    cursor = parseInt(nc) || 0;
    scoreKeys.push(...ks);
  } while (cursor !== 0);
  let pts = 0, exact = 0, correct = 0;
  if (scoreKeys.length) {
    const scores = await kv.mget(...scoreKeys);
    scores.forEach(s => {
      if (!s) return;
      pts += s.pts || 0;
      if (s.pts === 3) exact++;
      if (s.pts >= 1) correct++;
    });
  }
  const predCount = (await kv.smembers(`predSet:${uid}`) || []).length;
  return { pts, exact, correct, predCount };
}

async function copyUserPredictionState(fromUid, toUid) {
  const matchIds = await kv.smembers(`predSet:${fromUid}`) || [];
  for (const id of matchIds) {
    const pred = await kv.get(`pred:${fromUid}:${id}`);
    if (pred) {
      await kv.set(`pred:${toUid}:${id}`, { ...pred, userId: toUid });
      await kv.sadd(`predSet:${toUid}`, String(id));
    }
    const score = await kv.get(`score:${fromUid}:${id}`);
    if (score) await kv.set(`score:${toUid}:${id}`, score);
  }
  const avatar = await kv.get(`avatar:${fromUid}`);
  if (avatar) await kv.set(`avatar:${toUid}`, avatar, { ex: 60 * 60 * 24 * 365 });
}

async function deletePredictorUser(uid, name) {
  await kv.del(`user:${uid}`);
  if (name) await kv.srem("names", name);
}

async function cleanupAutoGeneratedNameVariants(baseName, keepUid) {
  const variants = new Set([
    normName(baseName.slice(0, 18) + "2"),
    normName(baseName.slice(0, 17) + " FC"),
    normName(baseName + "2"),
  ]);
  let cursor = 0;
  do {
    const [nextCursor, keys] = await kv.scan(cursor, { match: "user:*", count: 100 });
    cursor = parseInt(nextCursor) || 0;
    for (const key of keys) {
      const uid = key.replace("user:", "");
      if (uid === keepUid) continue;
      const user = await kv.get(key);
      if (!user || !variants.has(normName(user.name))) continue;
      const preds = await kv.smembers(`predSet:${uid}`) || [];
      // Only delete empty auto-generated ghosts. If the user has picks, keep the account.
      if (preds.length === 0) await deletePredictorUser(uid, user.name);
    }
  } while (cursor !== 0);
}

export default async function handler(req, res) {
  cors(res);
  if (req.method === "OPTIONS") return res.status(200).end();

  const action = req.query.action;
  if (!action) return res.status(400).json({ error: "Missing action" });

  try {
    // ── register ──────────────────────────────────────────────────────────
    // POST { userId, name }
    // Saves a display name for a user. userId is a client-generated UUID.
    if (action === "register") {
      const { userId, name, avatar, city, country } = req.body || {};
      if (!userId || !name) return res.status(400).json({ error: "Missing userId or name" });
      const clean = name.trim().slice(0, 20);
      if (!clean) return res.status(400).json({ error: "Name too short" });

      let existing = await kv.get(`user:${userId}`);

      // If the same display name already exists under an old device ID, claim/migrate it
      // to the stable synced userId instead of creating Felipe2 / Felipe FC variants.
      const sameName = await findUserByName(clean);
      if (!existing && sameName && sameName.uid !== userId) {
        await copyUserPredictionState(sameName.uid, userId);
        await deletePredictorUser(sameName.uid, sameName.user?.name);
        existing = sameName.user || null;
        // If the merged-from user predates running totals on the user
        // record, compute them now rather than silently carrying forward
        // `undefined` (which downstream defaults to 0 and loses their score).
        if (existing && existing.pts === undefined) {
          const legacy = await computeLegacyTotals(sameName.uid);
          existing = { ...existing, ...legacy };
        }
      }

      if (existing?.name && normName(existing.name) !== normName(clean)) {
        await kv.srem("names", existing.name);
      }
      await kv.sadd("names", clean);

      // Store full avatar separately (supports base64 photos)
      if (avatar) {
        await kv.set(`avatar:${userId}`, avatar, { ex: 60 * 60 * 24 * 365 });
      }
      const userData = {
        userId, name: clean,
        hasAvatar: !!avatar || !!existing?.hasAvatar,
        city: city || existing?.city || "",
        country: country || existing?.country || "",
        registeredAt: existing?.registeredAt || Date.now(),
        // Running totals — maintained incrementally by savePred/score below
        // instead of recomputed from scratch on every leaderboard view (see
        // that handler for why this matters).
        pts: existing?.pts || 0,
        exact: existing?.exact || 0,
        correct: existing?.correct || 0,
        predCount: existing?.predCount || 0,
      };
      await kv.set(`user:${userId}`, userData);
      await cleanupAutoGeneratedNameVariants(clean, userId);
      return res.status(200).json({ userId, name: clean });
    }

    // ── getUser ───────────────────────────────────────────────────────────
    // GET ?action=getUser&userId=...
    if (action === "getUser") {
      const { userId } = req.query;
      if (!userId) return res.status(400).json({ error: "Missing userId" });
      const user = await kv.get(`user:${userId}`);
      return res.status(200).json(user || null);
    }

    // ── savePred ──────────────────────────────────────────────────────────
    // POST { userId, matchId, hg, ag }
    // Saves or updates a prediction. Only allowed before match kicks off
    // (enforcement is client-side for simplicity — the match UTC times are public).
    if (action === "savePred") {
      const { userId, matchId, hg, ag } = req.body || {};
      if (!userId || !matchId || hg === undefined || ag === undefined) {
        return res.status(400).json({ error: "Missing fields" });
      }
      // Verify user exists
      const user = await kv.get(`user:${userId}`);
      if (!user) return res.status(403).json({ error: "User not registered" });

      await kv.set(`pred:${userId}:${matchId}`, {
        userId, matchId,
        hg: parseInt(hg), ag: parseInt(ag),
        savedAt: Date.now()
      });
      // Add matchId to user's set of predicted matches. sadd returns the
      // number of elements actually added (0 if it was already a member),
      // so we only bump predCount on a genuinely new pick, not every edit.
      const added = await kv.sadd(`predSet:${userId}`, String(matchId));
      if (added > 0) {
        await kv.set(`user:${userId}`, { ...user, predCount: (user.predCount || 0) + 1 });
      }
      return res.status(200).json({ ok: true });
    }

    // ── getPreds ──────────────────────────────────────────────────────────
    // GET ?action=getPreds&userId=...
    // Returns all predictions for a user: { [matchId]: { hg, ag } }
    if (action === "getPreds") {
      const { userId } = req.query;
      if (!userId) return res.status(400).json({ error: "Missing userId" });
      const matchIds = await kv.smembers(`predSet:${userId}`) || [];
      if (!matchIds.length) return res.status(200).json({});
      const keys = matchIds.map(id => `pred:${userId}:${id}`);
      const values = await kv.mget(...keys);
      const result = {};
      matchIds.forEach((id, i) => {
        if (values[i]) result[id] = values[i];
      });
      return res.status(200).json(result);
    }

    // ── score ─────────────────────────────────────────────────────────────
    // POST { matchId, hg, ag }
    // Called when a match finishes (via webhook, cron, or manual trigger).
    // Scores all predictions for that match and updates leaderboard.
    // Protected by a simple shared secret in env.
    if (action === "score") {
      const secret = req.headers["x-admin-secret"];
      if (secret !== process.env.PREDICTOR_ADMIN_SECRET) {
        return res.status(401).json({ error: "Unauthorized" });
      }
      const { matchId, hg, ag } = req.body || {};
      if (!matchId || hg === undefined || ag === undefined) {
        return res.status(400).json({ error: "Missing fields" });
      }
      // Save the result
      await kv.set(`result:${matchId}`, { hg: parseInt(hg), ag: parseInt(ag), scoredAt: Date.now() });
      // Find all users who predicted this match
      const allUsers = await kv.smembers("names") || [];
      // Get all userIds
      const userIds = [];
      // Scan for all user keys (small dataset — fine to iterate)
      let cursor = 0;
      do {
        const [nextCursor, keys] = await kv.scan(cursor, { match: "user:*", count: 100 });
        cursor = parseInt(nextCursor) || 0;
        for (const key of keys) {
          const uid = key.replace("user:", "");
          userIds.push(uid);
        }
      } while (cursor !== 0);

      // Score each user
      let scored = 0;
      for (const uid of userIds) {
        const pred = await kv.get(`pred:${uid}:${matchId}`);
        if (!pred) continue;
        const pts = calcScore(pred, { hg: parseInt(hg), ag: parseInt(ag) });
        if (pts === null) continue;

        // Idempotent re-scoring: if this match was already scored for this
        // user (e.g. a correction after the result changed), subtract its
        // old contribution from the running totals before adding the new
        // one, instead of double-counting.
        const prevScore = await kv.get(`score:${uid}:${matchId}`);
        const user = await kv.get(`user:${uid}`);
        if (user) {
          const prevPts = prevScore?.pts || 0;
          const wasExact = prevScore?.pts === 3 ? 1 : 0;
          const wasCorrect = prevScore && prevScore.pts >= 1 ? 1 : 0;
          const isExact = pts === 3 ? 1 : 0;
          const isCorrect = pts >= 1 ? 1 : 0;
          await kv.set(`user:${uid}`, {
            ...user,
            pts: (user.pts || 0) - prevPts + pts,
            exact: (user.exact || 0) - wasExact + isExact,
            correct: (user.correct || 0) - wasCorrect + isCorrect,
          });
        }

        // Store per-match score
        await kv.set(`score:${uid}:${matchId}`, { pts, hg: parseInt(hg), ag: parseInt(ag), predHg: pred.hg, predAg: pred.ag });
        scored++;
      }
      return res.status(200).json({ ok: true, matchId, scored });
    }

    // ── leaderboard ───────────────────────────────────────────────────────
    // GET ?action=leaderboard
    // Returns sorted leaderboard by total points.
    //
    // This used to recompute every user's totals from scratch on every
    // single call: for each user, a full SCAN over their score:* keys, an
    // mget of all of them, and a separate smembers for predCount. That's
    // O(users × finished matches) Redis commands on every leaderboard view
    // — and it only gets worse as the tournament progresses and more
    // matches finish. With enough users polling this reasonably often, it
    // was very likely the single largest source of Redis load in the app.
    //
    // pts/exact/correct/predCount now live directly on the user record,
    // maintained incrementally by score/savePred. So this just needs one
    // SCAN for keys plus one mget for all user records — flat cost,
    // regardless of how many matches have finished.
    //
    // Self-healing migration: a user record created before this change
    // won't have these fields yet (`user.pts === undefined`, not just 0).
    // For exactly that user, on exactly their next leaderboard view, fall
    // back to the old scan-based computation once and persist the result
    // onto their record — every call after that is cheap for them too. No
    // separate manual migration step needed.
    if (action === "leaderboard") {
      const userIds = [];
      let cursor = 0;
      do {
        const [nextCursor, keys] = await kv.scan(cursor, { match: "user:*", count: 100 });
        cursor = parseInt(nextCursor) || 0;
        keys.forEach(k => userIds.push(k.replace("user:", "")));
      } while (cursor !== 0);

      if (!userIds.length) return res.status(200).json([]);

      const userKeys = userIds.map(uid => `user:${uid}`);
      const userRecords = await kv.mget(...userKeys);

      const results = await Promise.all(userIds.map(async (uid, i) => {
        const user = userRecords[i];
        if (!user) return null;

        let { pts, exact, correct, predCount } = user;
        if (pts === undefined) {
          // Pre-migration record — compute the old expensive way exactly
          // once, then persist so this branch never runs again for this user.
          const legacy = await computeLegacyTotals(uid);
          pts = legacy.pts; exact = legacy.exact; correct = legacy.correct; predCount = legacy.predCount;
          await kv.set(`user:${uid}`, { ...user, ...legacy });
        }

        return { userId: uid, name: user.name, hasAvatar: user.hasAvatar || false, city: user.city || "", country: user.country || "", pts: pts || 0, exact: exact || 0, correct: correct || 0, predCount: predCount || 0 };
      }));

      const sorted = results
        .filter(Boolean)
        .sort((a, b) => b.pts - a.pts || b.exact - a.exact || b.correct - a.correct);

      // Batch fetch avatars for users that have one
      const avatarUserIds = sorted.filter(e => e.hasAvatar).map(e => e.userId);
      const avatarMap = {};
      if (avatarUserIds.length) {
        const avatarKeys = avatarUserIds.map(uid => `avatar:${uid}`);
        const avatarValues = await kv.mget(...avatarKeys);
        avatarUserIds.forEach((uid, i) => {
          if (avatarValues[i]) avatarMap[uid] = avatarValues[i];
        });
      }

      const board = sorted.map(e => ({ ...e, avatar: avatarMap[e.userId] || null }));

      res.setHeader("Cache-Control", "public, max-age=10, s-maxage=20, stale-while-revalidate=60");
      return res.status(200).json(board);
    }

    // ── allPreds ──────────────────────────────────────────────────────────
    // GET ?action=allPreds&matchId=...
    // Returns everyone's prediction for a specific match (only after result saved).
    if (action === "allPreds") {
      const { matchId } = req.query;
      if (!matchId) return res.status(400).json({ error: "Missing matchId" });
      // Only reveal after match has a result
      const result = await kv.get(`result:${matchId}`);
      if (!result) return res.status(403).json({ error: "Match not finished yet" });

      // Scan for all predictions for this match
      const preds = [];
      let cursor = 0;
      do {
        const [nc, keys] = await kv.scan(cursor, { match: `pred:*:${matchId}`, count: 100 });
        cursor = parseInt(nc);
        if (keys.length) {
          const uids = keys.map(k => k.split(":")[1]);
          // Was 2 individual kv.get calls per prediction (user + score) in
          // a loop — batched into 2 mgets total per scan page instead,
          // regardless of how many predictions are in that page.
          const [vals, users, scores] = await Promise.all([
            kv.mget(...keys),
            kv.mget(...uids.map(uid => `user:${uid}`)),
            kv.mget(...uids.map(uid => `score:${uid}:${matchId}`)),
          ]);
          for (let i = 0; i < keys.length; i++) {
            if (!vals[i]) continue;
            preds.push({
              name: users[i]?.name || "Unknown",
              hg: vals[i].hg,
              ag: vals[i].ag,
              pts: scores[i]?.pts ?? null,
            });
          }
        }
      } while (cursor !== 0);

      res.setHeader("Cache-Control", "public, max-age=30, s-maxage=60");
      return res.status(200).json({ result, preds: preds.sort((a,b) => (b.pts||0)-(a.pts||0)) });
    }

    return res.status(404).json({ error: `Unknown action: ${action}` });

  } catch (err) {
    console.error(`[predictor] ${action} error:`, err.message);
    return res.status(500).json({ error: err.message });
  }
}
